name: bluetooth_printer_app
description: A Flutter app for testing Bluetooth receipt printers.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  thermal_printer: ^1.0.5
  esc_pos_utils_plus: ^2.0.4
  permission_handler: ^11.3.0
  shared_preferences: ^2.2.2
  flutter_riverpod: ^2.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
